export interface FallbackEvent {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  category: string;
  club: string;
  venue: string;
  venue2?: string;
  duration: string;
  startTime: string;
  endTime: string;
  capacity: number;
  registrationOpen: boolean;
  registeredCount: number;
  remainingSpots: number;
  status: "OPEN" | "LIMITED" | "ALMOST_FULL" | "HOUSEFULL" | "CLOSED";
  posterImage: string;
  description: string;
  rules: string;
  maxTeamSize: number;
  isTeamEvent: boolean;
  teamSizeLabel: string;
  certificates: string | number;
  pocName: string;
  pocDept: string;
  pocContact: string;
  requirements?: string;
  showType: "FDFS" | "SDFS";
  showLabel: string;
  tamilTitle: string;
}

export const FALLBACK_EVENTS: FallbackEvent[] = [
  // =========================================================================
  // FDFS: FIRST DAY FIRST SHOW (FRIDAY, SEPTEMBER 18, 2026) — 19 EVENTS
  // =========================================================================
  {
    id: "shutter-dare",
    name: "The Shutter Dare",
    slug: "shutter-dare",
    tagline: "2 photographers, 1 campus, high-shutter adrenaline dares.",
    category: "Photography",
    club: "SVCE PhotoClub",
    venue: "Block 3",
    venue2: "Block 5",
    duration: "2 hrs",
    startTime: "2026-09-18T10:00:00.000Z",
    endTime: "2026-09-18T12:00:00.000Z",
    capacity: 30,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 30,
    status: "OPEN",
    posterImage: "/posters/photography.svg",
    description: "Photo scavenger challenge by SVCE PhotoClub. Teams of 2 race across Block 3 & 5 to shoot cinematic stills adhering to spontaneous director prompts.",
    rules: "1. Exclusively for 1st Year Freshers (Batch 2026–2030).\n2. Team of 2 photographers.\n3. DSLR, mirrorless, and mobile submissions accepted in separate judging streams.\n4. No excessive generative AI manipulation.",
    maxTeamSize: 2,
    isTeamEvent: true,
    teamSizeLabel: "Team of 2",
    certificates: "6",
    pocName: "Sriram",
    pocDept: "Mechanical – II Year",
    pocContact: "9360921737",
    requirements: "Volunteers",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "தி ஷட்டர் டேர்",
  },
  {
    id: "saregama",
    name: "Saregama",
    slug: "saregama",
    tagline: "The definitive collegiate vocal & antakshari showdown.",
    category: "Music",
    club: "Rotaract Club",
    venue: "Classroom Block 5",
    venue2: "Classroom Block 3",
    duration: "10 AM–1 PM",
    startTime: "2026-09-18T10:00:00.000Z",
    endTime: "2026-09-18T13:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/singing.svg",
    description: "Rotaract Club's high-spirited musical face-off. Test your Kollywood song knowledge, classical swaras, and rapid vocal transition skills across multiple rounds.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Team size: 3 to 4 vocalists.\n3. Rapid-fire antakshari, tune identification, and medley mashups.\n4. Maximum 2 minutes per round.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3–4",
    certificates: "8",
    pocName: "Divyadharshini K",
    pocDept: "MN – 2nd Year",
    pocContact: "9342441570",
    requirements: "Speaker, Mic, Printables",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "சாரேகம",
  },
  {
    id: "dhuruvangal-pathinaaru",
    name: "Dhuruvangal Pathinaaru",
    slug: "dhuruvangal-pathinaaru",
    tagline: "16 investigative clues. 1 solo scientific mastermind.",
    category: "Science & Mystery",
    club: "SVCE Science Club",
    venue: "Block 3 – 1st Floor",
    venue2: "Block 5 – 1st Floor",
    duration: "4 hrs",
    startTime: "2026-09-18T09:30:00.000Z",
    endTime: "2026-09-18T13:30:00.000Z",
    capacity: 35,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 35,
    status: "OPEN",
    posterImage: "/posters/treasure.svg",
    description: "Inspired by procedural neo-noir thrillers, SVCE Science Club presents a high-stakes forensic investigative challenge requiring circuit logic, puzzle deciphering, and lateral deduction.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Individual participation.\n3. 16 procedural clue checkpoints across Block 3 & 5.\n4. Breadboards, resistors, and LED verification required.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "2",
    pocName: "Adhitya R",
    pocDept: "EEE – 3rd Year",
    pocContact: "9003547535",
    requirements: "Satin ribbons, colour papers, charts, glue, chalk, paper clips, sponge balls, connecting wires, balloons, paper cups, dice, breadboards, LEDs, resistors, Cello tape",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "துருவங்கள் பதினாறு",
  },
  {
    id: "veil-of-trust",
    name: "Veil of Trust",
    slug: "veil-of-trust",
    tagline: "Can you trust the signals when science bends perception?",
    category: "Science & Mystery",
    club: "Science Club",
    venue: "Block 5",
    venue2: "Block 5",
    duration: "3 hrs",
    startTime: "2026-09-18T13:30:00.000Z",
    endTime: "2026-09-18T16:30:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/treasure.svg",
    description: "Solo psychological and scientific experiment maze. Navigate sensory puzzles, deceit detection, and experimental hypothesis testing.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Individual entry.\n3. Scientific observation and reasoning tasks in Block 5.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "2–3",
    pocName: "Adithiya",
    pocDept: "EEE – 3rd Year",
    pocContact: "9003547535",
    requirements: "The necessary",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "நம்பிக்கை திரை",
  },
  {
    id: "tendkotta",
    name: "Tendkotta",
    slug: "tendkotta",
    tagline: "Vintage tent touring cinema vibes with rapid buzzer challenges.",
    category: "Cinema & Fun",
    club: "YRC",
    venue: "Block 5",
    venue2: "Block 3",
    duration: "2 hrs",
    startTime: "2026-09-18T11:00:00.000Z",
    endTime: "2026-09-18T13:00:00.000Z",
    capacity: 32,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 32,
    status: "OPEN",
    posterImage: "/posters/film.svg",
    description: "YRC brings the authentic rural tent kotta cinema atmosphere to SVCE. Teams of 4 compete in movie poster recognition, scene recreation, and Kollywood pop trivia.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. 2 projection rooms with tent cinema atmosphere.\n4. Written prelims followed by cinematic buzzer round.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "8",
    pocName: "Elamukhil K",
    pocDept: "Chemical Engineering – 3rd Year",
    pocContact: "9750029993",
    requirements: "2 rooms with projector, tent kotta, balloons, movie colour prints, colour chalk, chairs if possible",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "தெண்ட்கொட்டா",
  },
  {
    id: "mankatha-ecell",
    name: "MANKATHA",
    slug: "mankatha",
    tagline: "INR 5,000 Prize Pool. High-stakes entrepreneurial gamble.",
    category: "Strategy & Gaming",
    club: "E-CELL",
    venue: "Block 5 – 501",
    venue2: "Block 5 – 502",
    duration: "3 hrs",
    startTime: "2026-09-18T10:00:00.000Z",
    endTime: "2026-09-18T13:00:00.000Z",
    capacity: 40,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 40,
    status: "OPEN",
    posterImage: "/posters/gaming.svg",
    description: "No guts, no glory. E-CELL brings an adrenaline-fueled business simulation and risk-taking game inspired by the legendary casino heist thriller.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 2.\n3. Round 1: Market bidding & seed capital; Round 2: Crisis gamble & negotiation.\n4. INR 5,000 total prize pool.",
    maxTeamSize: 2,
    isTeamEvent: true,
    teamSizeLabel: "Team of 2",
    certificates: "15",
    pocName: "Kaviyarasan S",
    pocDept: "EEE – 3rd Year",
    pocContact: "7010673879",
    requirements: "INR 5,000 prize pool, projector + screen, HDMI cable/adapter, stable internet, speakers, 2 microphones, duster & chalk, decorative items",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "மங்காத்தா",
  },
  {
    id: "naan-avan-illai",
    name: "NAAN AVAN ILLAI",
    slug: "naan-avan-illai",
    tagline: "Deception, dual avatars, and instant role reversals.",
    category: "Theatre & Acting",
    club: "ShortFilm Club",
    venue: "Classroom Block 5",
    venue2: "Classroom Block 5",
    duration: "2–2.5 hrs",
    startTime: "2026-09-18T14:00:00.000Z",
    endTime: "2026-09-18T16:30:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/drama.svg",
    description: "ShortFilm Club's high-energy character imitation and improv acting game. Convince the jury you are someone entirely different in hilarious scenario prompts.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 2 to 3 actors.\n3. Spontaneous character swap upon whistle cue.\n4. 5 to 7 minutes on stage.",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 2–3",
    certificates: "6",
    pocName: "Vigneshwar",
    pocDept: "ECE – 2nd Year",
    pocContact: "8939399509",
    requirements: "NIL",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "நான் அவன் இல்லை",
  },
  {
    id: "cinema-cinema-day1",
    name: "Cinema, Cinema! – Day 1",
    slug: "cinema-cinema-day1",
    tagline: "Pure cinephile monologue, dialogue dubbing, and screening review.",
    category: "Cinema & Film",
    club: "ShortFilm Club",
    venue: "Library Seminar Hall",
    venue2: "Library Seminar Hall",
    duration: "3 hrs",
    startTime: "2026-09-18T10:00:00.000Z",
    endTime: "2026-09-18T13:00:00.000Z",
    capacity: 30,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 30,
    status: "OPEN",
    posterImage: "/posters/film.svg",
    description: "Showcase your cinephilia! Deliver iconic movie monologues, live dialogue syncs, and scene breakdowns evaluated by ShortFilm Club leads.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo performance.\n3. Round 1: Iconic monologue recreation; Round 2: Mute video live dubbing.\n4. Time limit: 4 minutes per participant.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "NIL",
    pocName: "Annirudh",
    pocDept: "Mechanical – 2nd Year",
    pocContact: "9080244160",
    requirements: "Mic, Speaker",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "சினிமா, சினிமா! (நாள் 1)",
  },
  {
    id: "trace-and-tell",
    name: "TRACE & TELL",
    slug: "trace-and-tell",
    tagline: "Trace the brand story, narrate the pitch under pressure.",
    category: "Media & Marketing",
    club: "Marketing & Communication Club",
    venue: "Classroom Block 3 – 1st Floor",
    venue2: "Classroom Block 5",
    duration: "3 hrs (9 AM–12 PM)",
    startTime: "2026-09-18T09:00:00.000Z",
    endTime: "2026-09-18T12:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/quiz.svg",
    description: "Marketing & Communication Club presents a dynamic brand narrative and visual telemetry game where teams trace clues to pitch products live on mic.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 3 members.\n3. Digitek mic broadcast round for live sales pitches.\n4. Judging based on wit, clarity, and crowd impact.",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3",
    certificates: "6",
    pocName: "Santhoshkumar C",
    pocDept: "EEE – 3rd Year",
    pocContact: "9080083869",
    requirements: "Digitek mic",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "ட்ரேஸ் & டெல்",
  },
  {
    id: "kollywood-dive-lokesh",
    name: "Kollywood Dive ft. Lokesh Kanagaraj",
    slug: "kollywood-dive-lokesh",
    tagline: "Dissect cinematic universes, Easter eggs, and dark hero arcs.",
    category: "Pop Culture & Literature",
    club: "Reading Club",
    venue: "Block 5",
    venue2: "Block 3",
    duration: "2–3 hrs",
    startTime: "2026-09-18T13:30:00.000Z",
    endTime: "2026-09-18T16:30:00.000Z",
    capacity: 28,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 28,
    status: "OPEN",
    posterImage: "/posters/film.svg",
    description: "Reading Club leads a deep dive into modern Tamil cinematic universes. Teams explore nonlinear scripts, cinematic motifs, and world-building puzzles.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. Script analysis, timeline decoding, and cinematic trivia.\n4. 3 rounds of intense buzzer action.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "8",
    pocName: "Nethra Ravichandran",
    pocDept: "Biotech – 2nd Year",
    pocContact: "7868855428",
    requirements: "NIL",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "கோலிவுட் டைவ் ஃபீட். லோகேஷ் கனகராஜ்",
  },
  {
    id: "clue-lywood",
    name: "Clue-lywood",
    slug: "clue-lywood",
    tagline: "Engineering logic meets Kollywood puzzle tracks.",
    category: "Adventure & Logic",
    club: "Engineers Without Borders",
    venue: "Classroom Block 5",
    venue2: "Classroom Block 3",
    duration: "2 hrs",
    startTime: "2026-09-18T14:00:00.000Z",
    endTime: "2026-09-18T16:00:00.000Z",
    capacity: 30,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 30,
    status: "OPEN",
    posterImage: "/posters/treasure.svg",
    description: "Engineers Without Borders challenges freshers with engineering-inspired clues veiled in Tamil cinema references. Decode equations to unlock secret campus coordinates.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. Paper puzzles, coordinate deciphering, and lateral logic.\n4. 2 hours time limit.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "8",
    pocName: "Gokul S",
    pocDept: "Biotechnology – III Year",
    pocContact: "9884463837",
    requirements: "Stationery items – colour papers, tape, etc.",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "க்ளூ-லிவுட்",
  },
  {
    id: "athimbir-innu-saagala-da",
    name: "Athimbir Innu Saagala Da",
    slug: "athimbir-innu-saagala-da",
    tagline: "Expressive poster art & cinematic black-chart visual creations.",
    category: "Creative Arts",
    club: "ISTD",
    venue: "Classroom Block 5",
    venue2: "Classroom Block 5",
    duration: "9:30 AM–1 PM",
    startTime: "2026-09-18T09:30:00.000Z",
    endTime: "2026-09-18T13:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/drama.svg",
    description: "ISTD’s high-energy theatrical art and visual storytelling showdown. Use red glass filters, acrylic paints, and dramatic silhouettes to depict iconic movie moments.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. Materials provided: red glass sheets, poster paints, black charts, sketch pens.\n4. Theme revealed at start of competition.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "8",
    pocName: "Sai Raksheedha S",
    pocDept: "ECE – IV Year",
    pocContact: "9345992882",
    requirements: "Red glass sheets, red poster paint, black charts, light colour charts, sketch pens, black markers, transparent cello tape",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "அத்திம்பேர் இன்னும் சாகல டா",
  },
  {
    id: "en-vazhi-thani-vazhi",
    name: "En Vazhi, Thani Vazhi",
    slug: "en-vazhi-thani-vazhi",
    tagline: "Solo dance clash. Unleash your signature style on the MPH stage.",
    category: "Dance",
    club: "SVCE Dance Club",
    venue: "MPH",
    venue2: "—",
    duration: "2 hrs",
    startTime: "2026-09-18T10:00:00.000Z",
    endTime: "2026-09-18T12:00:00.000Z",
    capacity: 35,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 35,
    status: "OPEN",
    posterImage: "/posters/dance.svg",
    description: "SVCE Dance Club’s premier solo dance championship for 1st years. Contemporary, hip-hop, western, or classical fusion with pure stage dominance.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo dance entry.\n3. Performance time: 3 to 4 minutes.\n4. Audio tracks to be submitted 1 hour before call time.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "2",
    pocName: "Varshini",
    pocDept: "CSE – III Year",
    pocContact: "94459 61281",
    requirements: "Sound system, trophies, judge refreshments, MC",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "என் வழி, தனி வழி",
  },
  {
    id: "gumbale-govindha",
    name: "Gumbale Govindha",
    slug: "gumbale-govindha",
    tagline: "Mass group kuthu choreography. When the gang steps out, the hall erupts.",
    category: "Dance",
    club: "SVCE Dance Club",
    venue: "MPH",
    venue2: "—",
    duration: "1.5–2 hrs",
    startTime: "2026-09-18T12:30:00.000Z",
    endTime: "2026-09-18T14:30:00.000Z",
    capacity: 30,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 30,
    status: "OPEN",
    posterImage: "/posters/dance.svg",
    description: "The ultimate first-year crew dance warfare! Synchronized high-octane Chennai kuthu, energetic formations, and crowd-electrifying hook steps.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad size: 2 to 8 dancers.\n3. Time limit: 5 to 7 minutes.\n4. Props allowed with prior approval.",
    maxTeamSize: 8,
    isTeamEvent: true,
    teamSizeLabel: "Group (2+)",
    certificates: "4+",
    pocName: "Swathi",
    pocDept: "CSE – III Year",
    pocContact: "96551 81692",
    requirements: "Sound system, trophies, judge refreshments, MC",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "கும்பலே கோவிந்தா",
  },
  {
    id: "aaatama-therottama",
    name: "Aaatama Therottama",
    slug: "aaatama-therottama",
    tagline: "Retro 80s & 90s classical and folk rhythm showdown.",
    category: "Dance",
    club: "SVCE Dance Club",
    venue: "MPH",
    venue2: "—",
    duration: "2 hrs",
    startTime: "2026-09-18T15:00:00.000Z",
    endTime: "2026-09-18T17:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/dance.svg",
    description: "Celebrate vintage Tamil cinema dance! Fast-paced rhythm transitions, expressive abhinaya, and classic Ilaiyaraaja-era footwork.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo dance entry.\n3. Must feature 80s or 90s Kollywood tracks.\n4. Time: 3 to 5 minutes.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "2",
    pocName: "Avanthika",
    pocDept: "CSE – III Year",
    pocContact: "72006 04074",
    requirements: "Sound system, DJ, trophies, judge refreshments, MC",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "ஆட்டமா தேரோட்டமா",
  },
  {
    id: "whats-the-channel",
    name: "What’s the Channel? – Channel Surfing",
    slug: "whats-the-channel",
    tagline: "Instant genre switching at the click of a remote.",
    category: "Theatre & Improv",
    club: "Curtain Call",
    venue: "Library Seminar Hall",
    venue2: "Block 5",
    duration: "4–5 hrs",
    startTime: "2026-09-18T10:00:00.000Z",
    endTime: "2026-09-18T15:00:00.000Z",
    capacity: 20,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 20,
    status: "OPEN",
    posterImage: "/posters/drama.svg",
    description: "Curtain Call's legendary comedy theatre event. Teams act out live television scenes, switching instantly between soap opera, breaking news, sports commentary, and mass cinema.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 4 to 5 actors.\n3. Judge changes channel via buzzer; teams must switch genre instantly without hesitation.\n4. Total time: 5 minutes.",
    maxTeamSize: 5,
    isTeamEvent: true,
    teamSizeLabel: "Groups of 4–5",
    certificates: "6",
    pocName: "Ajay B",
    pocDept: "CSE – 3rd Year",
    pocContact: "9841166133",
    requirements: "Projector, microphone, 4 tables",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "சேனல் சர்ஃபிங்",
  },
  {
    id: "mankatha-mode",
    name: "Mankatha Mode",
    slug: "mankatha-mode",
    tagline: "Quick reflexes, carnival agility, and trick shots.",
    category: "Campus Life & Fun",
    club: "Care Club",
    venue: "Block 5 – Ground Floor",
    venue2: "Block 3",
    duration: "2 hrs",
    startTime: "2026-09-18T14:00:00.000Z",
    endTime: "2026-09-18T16:00:00.000Z",
    capacity: 35,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 35,
    status: "OPEN",
    posterImage: "/posters/gaming.svg",
    description: "Care Club brings playful carnival agility challenges. Solo participants tackle rapid ping-pong bounce runs, cone weaves, and cup stack elimination rounds.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo obstacle challenge.\n3. Timed agility and ball bounce rounds.\n4. Top 6 fastest timings qualify for finals.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "4",
    pocName: "Prithish A S",
    pocDept: "CSE – 2nd Year",
    pocContact: "9486633947",
    requirements: "Paper cups, sponge balls, ping-pong balls, tape, cones",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "மங்காத்தா மோட்",
  },
  {
    id: "isai-express",
    name: "Isai Express",
    slug: "isai-express",
    tagline: "Full-day musical express across decades of Kollywood melody.",
    category: "Music",
    club: "Music Club SVCE",
    venue: "Classroom Block 5",
    venue2: "Classroom Block 3",
    duration: "Full day – 2 sessions",
    startTime: "2026-09-18T09:30:00.000Z",
    endTime: "2026-09-18T16:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/bands.svg",
    description: "Music Club SVCE's day-long acoustic and melody marathon. Teams of 3 race through song recall, live vocal harmonies, and ragam identification.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 3 vocalists/musicians.\n3. Session 1: Prelims & melody recall; Session 2: Live acoustic performance.\n4. Maximum 1 accompanying instrument.",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3",
    certificates: "6",
    pocName: "M S Rohith",
    pocDept: "Biotech – 3rd Year",
    pocContact: "+91 63744 93959",
    requirements: "Bluetooth speaker, microphone",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "இசை எக்ஸ்பிரஸ்",
  },
  {
    id: "iyal-isai-nadagam",
    name: "Iyal Isai Nadagam",
    slug: "iyal-isai-nadagam",
    tagline: "Literature, melody, and dramatic staging in pure Tamil heritage.",
    category: "Tamil Arts & Culturals",
    club: "Thendral Tamil Mandram",
    venue: "Block 5 – 506",
    venue2: "Block 5 Classroom",
    duration: "3 hrs",
    startTime: "2026-09-18T13:00:00.000Z",
    endTime: "2026-09-18T16:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/drama.svg",
    description: "Thendral Tamil Mandram's prestigious tripartite cultural celebration. Freshers present poetry recitation, classical and folk singing, and mini theatrical dialogues.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 3 members.\n3. Segment 1: Iyal (Poetry & Oratory); Segment 2: Isai (Vocal melody); Segment 3: Nadagam (Theatrical sketch).\n4. Total time: 10 minutes.",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3",
    certificates: "6",
    pocName: "Shivani",
    pocDept: "ECE – 2nd Year",
    pocContact: "8122198398",
    requirements: "Working speaker and projector",
    showType: "FDFS",
    showLabel: "FDFS: First Day First Show (Sept 18)",
    tamilTitle: "இயல் இசை நாடகம்",
  },

  // =========================================================================
  // SDFS: SECOND DAY FIRST SHOW (SATURDAY, SEPTEMBER 19, 2026) — 13 EVENTS
  // =========================================================================
  {
    id: "kadhaiya-kandu-pidi",
    name: "Kadhaiya Kandu Pidi",
    slug: "kadhaiya-kandu-pidi",
    tagline: "Unravel the hidden storyline from a series of photographic frames.",
    category: "Photography & Storytelling",
    club: "SVCE PhotoClub",
    venue: "Online",
    venue2: "—",
    duration: "2 hrs",
    startTime: "2026-09-19T10:00:00.000Z",
    endTime: "2026-09-19T12:00:00.000Z",
    capacity: 40,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 40,
    status: "OPEN",
    posterImage: "/posters/photography.svg",
    description: "Online photo narrative decryption by SVCE PhotoClub. Decode narrative sequences, lighting symbolism, and framing cues to reconstruct the director's plot.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 2.\n3. Conducted live via designated online platform.\n4. Time-bound submission of decoded scene plot.",
    maxTeamSize: 2,
    isTeamEvent: true,
    teamSizeLabel: "Team of 2",
    certificates: "6",
    pocName: "Yuvakannan",
    pocDept: "CSE – II Year",
    pocContact: "+91 98947 81390",
    requirements: "NA",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "கதையை கண்டு பிடி",
  },
  {
    id: "rotaract-spotlight",
    name: "2nd Event – Yet to be Decided",
    slug: "rotaract-spotlight",
    tagline: "Rotaract Club's secret mystery spotlight event.",
    category: "Trivia & Cultural",
    club: "Rotaract Club",
    venue: "CB 5",
    venue2: "CB 3",
    duration: "10 AM–1 PM",
    startTime: "2026-09-19T10:00:00.000Z",
    endTime: "2026-09-19T13:00:00.000Z",
    capacity: 30,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 30,
    status: "OPEN",
    posterImage: "/posters/quiz.svg",
    description: "Special mystery cultural showdown organized by Rotaract Club for first-year freshers. Fast-paced individual buzzer and talent round.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Individual entry.\n3. Full round structure revealed on Day 2 morning.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "2",
    pocName: "Kaavya B",
    pocDept: "EE – 2nd Year",
    pocContact: "9384825167",
    requirements: "Yet to be decided",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "ரோட்ராக்ட் ஸ்பாட்லைட்",
  },
  {
    id: "marmadesam",
    name: "Marmadesam",
    slug: "marmadesam",
    tagline: "Occult mysteries meets rigorous scientific skepticism.",
    category: "Science & Mystery",
    club: "SVCE Science Club",
    venue: "Block 3 – 1st Floor",
    venue2: "Block 5 – 1st Floor",
    duration: "4 hrs",
    startTime: "2026-09-19T09:30:00.000Z",
    endTime: "2026-09-19T13:30:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/treasure.svg",
    description: "SVCE Science Club reconstructs an enigmatic thriller. Teams untangle cryptic woollen connection boards, decipher coded chemical messages, and debunk supernatural hoaxes.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 3 members.\n3. 4-hour immersive science mystery investigation.\n4. Evidence boards & woollen thread correlation.",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3",
    certificates: "3",
    pocName: "Sanchitha D",
    pocDept: "ECE – 3rd Year",
    pocContact: "9787876126",
    requirements: "Double-sided tape, glitter paper, CD markers, colour pens, woollen thread",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "மர்மதேசம்",
  },
  {
    id: "dumbcharades",
    name: "Dumbcharades",
    slug: "dumbcharades",
    tagline: "Zero words, pure body language, maximum Kollywood laughter.",
    category: "Cinema & Fun",
    club: "YRC",
    venue: "Block 5",
    venue2: "Block 3",
    duration: "2 hrs",
    startTime: "2026-09-19T11:00:00.000Z",
    endTime: "2026-09-19T13:00:00.000Z",
    capacity: 35,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 35,
    status: "OPEN",
    posterImage: "/posters/film.svg",
    description: "YRC presents the classic Dumbcharades with a high-stakes cinema twist. Enact obscure movie titles, iconic mass scenes, and famous punch dialogues under tight timers.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. No lip movement or writing in the air.\n4. Round 1: Film titles; Round 2: Scene & dialogue recreation.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "8",
    pocName: "Lieogin Punniya Neson R S",
    pocDept: "Chemical – 3rd Year",
    pocContact: "9677770427",
    requirements: "Balloons, movie colour prints, colour chalk",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "டம்ப்ஷராட்ஸ்",
  },
  {
    id: "startup-survivor",
    name: "Startup Survivor",
    slug: "startup-survivor",
    tagline: "Can your student venture survive boardroom chaos and crisis cards?",
    category: "Entrepreneurship",
    club: "E-CELL",
    venue: "Seminar Hall",
    venue2: "Classroom Block 5",
    duration: "1.5 hrs",
    startTime: "2026-09-19T14:00:00.000Z",
    endTime: "2026-09-19T15:30:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/gaming.svg",
    description: "E-CELL's intense entrepreneurial crisis management arena. Face sudden market crashes, angel investor grilling, and resource allocation crises.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. 90-minute fast-paced startup survival simulation.\n4. Dynamic crisis cards drawn every 15 minutes.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "2",
    pocName: "Jai Ganesh S",
    pocDept: "AI&DS – 3rd Year",
    pocContact: "9360232663",
    requirements: "Projector, laptop, microphone, speakers, timer, printed problem cards, crisis cards, virtual money/resource cards",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "ஸ்டார்ட்அப் சர்வைவர்",
  },
  {
    id: "jigarthanda-shortfilm",
    name: "JIGARTHANDA – “Oru Padam Kaattavaa?”",
    slug: "jigarthanda",
    tagline: "Bold storytelling, gangland flair, and raw short film craft.",
    category: "Cinema & Short Film",
    club: "ShortFilm Club",
    venue: "Classroom Block 5",
    venue2: "Classroom Block 5",
    duration: "3 hrs",
    startTime: "2026-09-19T10:00:00.000Z",
    endTime: "2026-09-19T13:00:00.000Z",
    capacity: 20,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 20,
    status: "OPEN",
    posterImage: "/posters/film.svg",
    description: "ShortFilm Club's flagship film contest! Freshers screen their original short films or pitched scenes judged by senior filmmakers and student directors.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Crew size: 2 to 5 members.\n3. Maximum film runtime: 10 minutes including credits.\n4. 1080p MP4 format with English subtitles.",
    maxTeamSize: 5,
    isTeamEvent: true,
    teamSizeLabel: "Team of 2–5",
    certificates: "15",
    pocName: "Harshitha",
    pocDept: "ECE – 2nd Year",
    pocContact: "+91 98407 38712",
    requirements: "NIL",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "ஜிகர்தண்டா – “ஒரு படம் காட்டவா?”",
  },
  {
    id: "cinema-cinema-day2",
    name: "Cinema, Cinema! – Day 2",
    slug: "cinema-cinema-day2",
    tagline: "Day 2 Grand Cinephile Championship finale.",
    category: "Cinema & Film",
    club: "ShortFilm Club",
    venue: "Library Seminar Hall",
    venue2: "Library Seminar Hall",
    duration: "3 hrs",
    startTime: "2026-09-19T13:30:00.000Z",
    endTime: "2026-09-19T16:30:00.000Z",
    capacity: 30,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 30,
    status: "OPEN",
    posterImage: "/posters/film.svg",
    description: "Second edition of ShortFilm Club's film knowledge and dubbing arena. Spot the cinematography frame, imitate classic directors, and claim the ultimate cinephile bragging rights.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo performance.\n3. Live scene recreation and background score recognition.\n4. 3 rounds of elimination.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "NIL",
    pocName: "Nikhil",
    pocDept: "Mechanical – 2nd Year",
    pocContact: "9790899299",
    requirements: "NIL",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "சினிமா, சினிமா! (நாள் 2)",
  },
  {
    id: "sell-me-this",
    name: "Sell Me This",
    slug: "sell-me-this",
    tagline: "Pitch bizarre products with irresistible mass swagger.",
    category: "Marketing & Pitching",
    club: "Marketing & Communication Club",
    venue: "Biotech Function Hall",
    venue2: "Classroom Block 3",
    duration: "3 hrs (9 AM–12 PM)",
    startTime: "2026-09-19T09:00:00.000Z",
    endTime: "2026-09-19T12:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/fashion.svg",
    description: "Wolf of Wall Street meets Kollywood street-smart selling! Marketing & Communication Club tasks teams with pitching outlandish items to a skeptical panel.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 3.\n3. 2 minutes prep time, 3 minutes elevator pitch.\n4. Objections from judges must be tackled live.",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3",
    certificates: "6",
    pocName: "Logeshwaran P",
    pocDept: "ECE – 3rd Year",
    pocContact: "+91 74188 81692",
    requirements: "NIL",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "செல் மீ திஸ்",
  },
  {
    id: "hunter-license-test",
    name: "Hunter License Test",
    slug: "hunter-license-test",
    tagline: "Survival, wit, and anime-pop-culture strategy trials.",
    category: "Pop Culture & Lore",
    club: "Reading Club",
    venue: "Block 5",
    venue2: "Block 3",
    duration: "2–3 hrs",
    startTime: "2026-09-19T13:00:00.000Z",
    endTime: "2026-09-19T15:30:00.000Z",
    capacity: 32,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 32,
    status: "OPEN",
    posterImage: "/posters/gaming.svg",
    description: "Reading Club's multi-stage survival trial! Teams face stamina logic riddles, pop culture lore quizzes, and tactical negotiation rounds to win the prestigious Hunter License.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Squad of 4 members.\n3. Phase 1: Logic endurance run; Phase 2: Pop culture knowledge; Phase 3: Tactical face-off.",
    maxTeamSize: 4,
    isTeamEvent: true,
    teamSizeLabel: "Team of 4",
    certificates: "8",
    pocName: "Meenatshi P",
    pocDept: "CSE – 2nd Year",
    pocContact: "63748 25792",
    requirements: "NIL",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "ஹண்டர் லைசென்ஸ் தேர்வு",
  },
  {
    id: "lights-camera-care",
    name: "Lights, Camera, CARE!!!",
    slug: "lights-camera-care",
    tagline: "Empathy, student life situations, and cinematic enactments.",
    category: "Campus Life & Fun",
    club: "Care Club",
    venue: "Block 5",
    venue2: "Block 3",
    duration: "2 hrs",
    startTime: "2026-09-19T11:00:00.000Z",
    endTime: "2026-09-19T13:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/drama.svg",
    description: "Care Club blends social empathy with movie drama. Duos are given everyday college social situations and must dramatize an uplifting cinematic resolution.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 2.\n3. 5-minute sketch depicting an empathetic resolution to student conflicts.\n4. Evaluated on emotional resonance and stage craft.",
    maxTeamSize: 2,
    isTeamEvent: true,
    teamSizeLabel: "Team of 2",
    certificates: "4",
    pocName: "Suhan",
    pocDept: "EEE – 3rd Year",
    pocContact: "8148811608",
    requirements: "Speakers, projector",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "லைட்ஸ், கேமரா, கேர்!",
  },
  {
    id: "raga-of-revenge",
    name: "Raga of Revenge",
    slug: "raga-of-revenge",
    tagline: "High-octane vocal face-off. Pitch your voice against intense beats.",
    category: "Music",
    club: "Music Club SVCE",
    venue: "MPH",
    venue2: "Other Hall",
    duration: "3 hrs",
    startTime: "2026-09-19T10:00:00.000Z",
    endTime: "2026-09-19T13:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/singing.svg",
    description: "Music Club SVCE's dramatic solo vocal war! Sing emotional vengeance themes, adrenaline high-pitch tracks, and mass hero themes in 1-on-1 vocal face-offs.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo vocal contest.\n3. Round 1: High-intensity theme song; Round 2: 1-on-1 head-to-head acoustic duel.\n4. Microphones provided.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "3",
    pocName: "Aarti B S",
    pocDept: "ECE – 3rd Year",
    pocContact: "+91 99419 03348",
    requirements: "2 microphones",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "ராக ஆஃப் ரிவெஞ்ச்",
  },
  {
    id: "thaalam-trip",
    name: "THAALAM TRIP",
    slug: "thaalam-trip",
    tagline: "Percussion, beatboxing, and rhythmic improvisation odyssey.",
    category: "Music",
    club: "Music Club SVCE",
    venue: "MPH",
    venue2: "MPH",
    duration: "2 hrs",
    startTime: "2026-09-19T14:00:00.000Z",
    endTime: "2026-09-19T16:00:00.000Z",
    capacity: 25,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 25,
    status: "OPEN",
    posterImage: "/posters/bands.svg",
    description: "An exploration of rhythm and beats by Music Club SVCE. Solo percussionists, beatboxers, and konnakol artists showcase rhythmic dexterity on the MPH mainstage.",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Solo rhythm entry.\n3. Performance time: 4 to 5 minutes.\n4. Drums, cajon, mridangam, beatboxing, or hybrid beats permitted.",
    maxTeamSize: 1,
    isTeamEvent: false,
    teamSizeLabel: "Individual",
    certificates: "2",
    pocName: "Raviram Anbumani",
    pocDept: "IT – 3rd Year",
    pocContact: "+91 76049 45782",
    requirements: "3 microphones, 2 lead cables, 2 junction boxes",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "தாளம் ட்ரிப்",
  },
  {
    id: "ozhunga-paadu-spray",
    name: "Ozhunga Paadu Illa Spray Adichiduven",
    slug: "ozhunga-paadu-spray",
    tagline: "Sing in tune or face the water spray! Hilarious Tamil variety challenge.",
    category: "Tamil Arts & Culturals",
    club: "Thendral Tamil Mandram",
    venue: "Block 5 – 506",
    venue2: "Block 5 Classrooms",
    duration: "3 hrs",
    startTime: "2026-09-19T13:00:00.000Z",
    endTime: "2026-09-19T16:00:00.000Z",
    capacity: 35,
    registrationOpen: true,
    registeredCount: 0,
    remainingSpots: 35,
    status: "OPEN",
    posterImage: "/posters/drama.svg",
    description: "Thendral Tamil Mandram's crowd-favorite comedic singing game! Contestants must sing challenging Tamil lyrics without breaking meter or pitch—one false note and the spray triggers!",
    rules: "1. Exclusively for 1st Year Freshers.\n2. Teams of 3 members.\n3. Continuous Tamil song singing with spontaneous lyric and tongue-twister disruptions.\n4. Miss the note and your team gets sprayed!",
    maxTeamSize: 3,
    isTeamEvent: true,
    teamSizeLabel: "Team of 3",
    certificates: "6",
    pocName: "Shivani",
    pocDept: "ECE – 2nd Year",
    pocContact: "8122198398",
    requirements: "Speaker and projector",
    showType: "SDFS",
    showLabel: "SDFS: Second Day First Show (Sept 19)",
    tamilTitle: "ஒழுங்கா பாடு இல்ல ஸ்ப்ரே அடிச்சிடுவேன்",
  },
];

export function getFallbackEvent(idOrSlug: string): FallbackEvent | undefined {
  return FALLBACK_EVENTS.find((e) => e.id === idOrSlug || e.slug === idOrSlug);
}
